import streamlit as st
import requests
import datetime

# from exception.exceptions import TradingBotException
import sys

BASE_URL = "https://agentic-ai-trip-planner.onrender.com"  # Backend endpoint

st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        # # Show user message
        # Show thinking spinner while backend processes
        with st.spinner("Bot is thinking..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            markdown_content = f"""# 🌍 AI Travel Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
            # **Created by:** Atriyo's Travel Agent

            ---

            {answer}

            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """
            st.markdown(markdown_content)
        else:
            st.error(" Bot failed to respond: " + response.text)

    except Exception as e:
        st.error(f"The response failed due to: {e}")




#         Here's the full AI agent workflow for a trip planner. Click any node to dive deeper into how that component works.
# The workflow has six key stages:
# User input feeds destination, dates, budget, and preferences into an orchestrator agent that breaks the task into sub-goals and dispatches four specialist agents in parallel — flights, hotels, activities, and weather — each calling their respective external APIs.
# Results flow back into a reasoning + memory layer where options are ranked, conflicts resolved, and past preferences remembered. A constraint checker then validates against budget, visa rules, and date logic — if anything fails, it loops back to the orchestrator to retry with adjusted parameters.
# Finally, the itinerary builder assembles a day-by-day plan with maps and booking links, delivering the finished trip plan in the user's preferred format.